[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "numba>=0.61.0",
    "numpy>=2.1.3",
    "pyopencl>=2025.1",
]
